# Generated by Django 4.2.4 on 2023-12-06 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bookMng", "0004_shoppingcart_favorite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bookMng.book",
            ),
        ),
    ]
