# Generated by Django 4.2.4 on 2023-12-06 23:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookMng", "0006_book_current_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="current_owner",
            new_name="original_owner",
        ),
    ]
